name: Alineaid Automated Scraper

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: "0 0/2 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set global directory
        run: git config --global --add safe.directory /github/workspace

      - uses: actions/checkout@v3     
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            software-properties-common \
            gnupg \
            wget \
            gcc \
            python3-dev \
            unzip \
            chromium-browser
          pip install selenium cython bs4

      - name: Install Compatible ChromeDriver
        run: |
          # Get Chromium version
          CHROME_VERSION=$(chromium-browser --version | awk '{print $2}' | cut -d'.' -f1)
          echo "Detected Chromium Version: $CHROME_VERSION"

          # Get compatible ChromeDriver version
          DRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          echo "Detected ChromeDriver Version: $DRIVER_VERSION"

          # Download ChromeDriver
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip
          chromedriver --version

      - name: Build Cython Modules and Run Scraper
        run: |
          python setup.py build_ext --inplace
          python scraper.py --iterations 1000 --workers 15

      - name: Check for changes
        id: check_changes
        run: |
          git config --local user.email "belajarqywok@gmail.com"
          git config --local user.name "belajarqywok"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and Push Changes
        if: env.has_changes == 'true'
        run: |
          git commit -m "Update Datasets"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} main
