name: Alineaid Automated Scraper

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: "0 0/2 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set global directory
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3     
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Setup GPG for Chromium
        run: |
          echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster.gpg] http://deb.debian.org/debian buster main
          deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster-updates.gpg] http://deb.debian.org/debian buster-updates main
          deb [arch=amd64 signed-by=/usr/share/keyrings/debian-security-buster.gpg] http://deb.debian.org/debian-security buster/updates main' | sudo tee /etc/apt/sources.list.d/debian.list

          curl -fsSL https://ftp-master.debian.org/keys/archive-key-10.asc -o /usr/share/keyrings/debian-buster.gpg
          curl -fsSL https://ftp-master.debian.org/keys/archive-key-10.asc -o /usr/share/keyrings/debian-buster-updates.gpg
          curl -fsSL https://ftp-master.debian.org/keys/archive-key-10.asc -o /usr/share/keyrings/debian-security-buster.gpg

          echo 'Package: *
          Pin: release a=eoan
          Pin-Priority: 500

          Package: *
          Pin: origin "deb.debian.org"
          Pin-Priority: 300

          Package: chromium*
          Pin: origin "deb.debian.org"
          Pin-Priority: 700' | sudo tee /etc/apt/preferences.d/chromium.pref

      - name: Install Cython, Selenium, Chromium, etc.
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            gcc python3-dev gnupg chromium chromium-driver
          pip install selenium cython bs4

      - name: Install Chromium v90.0.4430.72
        run: |
          wget https://www.slimjet.com/chrome/download-chrome.php?file=files%2F90.0.4430.72%2Fgoogle-chrome-stable_current_amd64.deb
          sudo dpkg -i $(ls | grep .deb)
          rm $(ls | grep .deb)
          google-chrome-stable --version

      - name: Build Cython Modules and Run Scraper
        run: |
          python setup.py build_ext --inplace
          python scraper.py \
            --iterations 1000 --workers 15

      - name: Check for changes
        id: check_changes
        run: |
          git config --local user.email "belajarqywok@gmail.com"
          git config --local user.name "belajarqywok"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.has_changes == 'true'
        run: |
          git commit -m "Update Datasets"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} main
